window.RUMBLE_QUESTIONS = [
  {type:"Majority", text:"Wie zegt dit weekend ‘ik doe rustig aan’ met de energie van iemand die binnen 2 uur ontspoort?"},
  {type:"Majority", text:"Wie heeft de grootste kans om in Lille een volledig nieuw vriendengroepje te adopteren?"},
  {type:"Majority", text:"Wie verdwijnt het meest waarschijnlijk 25 minuten en komt terug met ‘ik was gewoon buiten’?"},
  {type:"Majority", text:"Wie bestelt in het Frans met zóveel zelfvertrouwen dat niemand durft te zeggen dat het fout was?"},
  {type:"Majority", text:"Wie gaat het eerst dramatisch honger hebben alsof de situatie humanitair wordt?"},
  {type:"Majority", text:"Wie gaat het hardst doen alsof hij/zij de route weet, terwijl Google Maps letterlijk openstaat?"},
  {type:"Majority", text:"Wie heeft de meeste kans om zondag wakker te worden met een verhaal dat klinkt alsof het verzonnen is?"},
  {type:"Majority", text:"Wie wordt dit weekend de onofficiële burgemeester van Lille?"},
  {type:"Majority", text:"Wie zegt ‘nog één drankje’ op een manier waarop iedereen weet: dit is geen één drankje?"},
  {type:"Majority", text:"Wie wordt emotioneel van een fout nummer alsof het speciaal voor hem/haar geschreven is?"},
  {type:"Majority", text:"Wie heeft de grootste kans om de hele avond met hetzelfde halfvolle drankje rond te lopen?"},
  {type:"Majority", text:"Wie maakt dit weekend de meest twijfelachtige financiële beslissing en noemt het daarna ‘investeren in herinneringen’?"},
  {type:"Majority", text:"Wie klaagt het hardst over de rekening maar bestelde zelf alsof de koning betaalde?"},
  {type:"Majority", text:"Wie flirt het meest zonder door te hebben dat het flirten is?"},
  {type:"Majority", text:"Wie maakt het snelst een beste vriend voor het leven in de wc-rij?"},
  {type:"Majority", text:"Wie wordt zó competitief over dit spel dat hij/zij gaat zeggen dat de regels oneerlijk zijn?"},
  {type:"Majority", text:"Wie gaat als eerste zeggen dat Lille ‘eigenlijk best romantisch’ is?"},
  {type:"Majority", text:"Wie eindigt waarschijnlijk op een foto waar later ‘verwijderen aub’ onder komt te staan?"},
  {type:"Majority", text:"Wie is de persoon die iedereen kwijt is terwijl hij/zij gewoon naast de groep staat?"},
  {type:"Majority", text:"Wie wordt de grootste liability bij het tankstation?"},
  {type:"Majority", text:"Wie vraagt als eerste ‘hoe ver is het nog?’ alsof we op kamp zijn?"},
  {type:"Majority", text:"Wie ontwikkelt in Lille waarschijnlijk een compleet alter ego?"},
  {type:"Majority", text:"Wie heeft de meeste ‘ik regel dit wel’-energie maar regelt uiteindelijk vooral paniek?"},
  {type:"Majority", text:"Wie zegt het vaakst ‘ik ben echt niet dronken’ met exact de stem van iemand die dat wel is?"},
  {type:"Majority", text:"Wie zou het beste kunnen liegen tegen de groep en ermee wegkomen?"},
  {type:"Majority", text:"Wie gebruikt het vaakst ‘ik ben volwassen’ in situaties die het tegenovergestelde bewijzen?"},
  {type:"Majority", text:"Wie wordt het snelst vrienden met personeel?"},
  {type:"Majority", text:"Wie laat zijn/haar telefoon op 3% staan en noemt dat ‘prima’?"},
  {type:"Majority", text:"Wie koopt het meest nutteloze souvenir en verdedigt het alsof het kunst is?"},
  {type:"Majority", text:"Wie doet het meest overtuigend alsof hij/zij voor cultuur naar Lille komt?"},
  {type:"Majority", text:"Wie vraagt zondagochtend het meest verdacht: ‘heb ik iets raars gedaan?’"},
  {type:"Roast", text:"Wie heeft de meest gevaarlijke combinatie van zelfvertrouwen en slechte ideeën?"},
  {type:"Roast", text:"Wie is de grootste kanshebber om zichzelf dit weekend volledig te exposen?"},
  {type:"Roast", text:"Wie sloopt een groepsplanning het snelst met de zin ‘ik heb een beter idee’?"},
  {type:"Roast", text:"Wie doet het vaakst ‘even snel’ iets en is dan drie kwartier weg?"},
  {type:"Roast", text:"Wie krijgt main character syndrome zodra er muziek aanstaat?"},
  {type:"Roast", text:"Wie praat zichzelf het makkelijkst uit een situatie die hij/zij zelf veroorzaakt heeft?"},
  {type:"Roast", text:"Wie heeft het hoogste ‘ik kan dit aan’-niveau met het laagste bewijs?"},
  {type:"Roast", text:"Wie ziet er het meest uit alsof hij/zij morgen zegt: ‘dit was niet mijn schuld’?"},
  {type:"Roast", text:"Wie heeft de meeste kans om een slecht idee te presenteren alsof het een businessplan is?"},
  {type:"Roast", text:"Wie gaat dit weekend het vaakst slachtoffer worden van eigen enthousiasme?"},
  {type:"Majority", text:"Wie wordt de groepsadvocaat als iemand een dom plan heeft?"},
  {type:"Majority", text:"Wie gaat de eerste zijn die ‘we moeten NU eten’ zegt?"},
  {type:"Majority", text:"Wie heeft het meeste kans om per ongeluk in een andere kroeg dan de rest te staan?"},
  {type:"Majority", text:"Wie maakt het meest dramatische entree in de eerste bar?"},
  {type:"Majority", text:"Wie gaat het hardst ontkennen dat hij/zij moe is terwijl de ogen al dichtvallen?"},
  {type:"Majority", text:"Wie is het meest waarschijnlijk om ineens DJ te willen zijn in de auto?"},
  {type:"Majority", text:"Wie heeft de grootste kans om een verhaal te beginnen met ‘oké luister…’ en dan wordt het verdacht?"},
  {type:"Majority", text:"Wie gaat zich gedragen alsof hij/zij Lille persoonlijk heeft ontdekt?"},
  {type:"Majority", text:"Wie wordt de persoon die bij elke bar zegt: ‘de volgende is beter’?"},
  {type:"Majority", text:"Wie gaat het eerste met iemand discussiëren over iets waar die eigenlijk niks van weet?"},
  {type:"Majority", text:"Wie heeft de grootste kans om de groep kwijt te raken omdat die ‘even een foto’ wilde maken?"},
  {type:"Majority", text:"Wie zou als eerste bij een random tafel aanschuiven alsof hij/zij uitgenodigd was?"},
  {type:"Majority", text:"Wie heeft de meeste kans om het weekend samen te vatten als ‘legendarisch’ nog vóór het begonnen is?"},
  {type:"Majority", text:"Wie gaat bij aankomst in Lille meteen doen alsof hij/zij locals begrijpt?"},
  {type:"Majority", text:"Wie wordt het hardst geraakt door de eerste slechte grap van de avond?"},
  {type:"Majority", text:"Wie heeft het meeste risico op een ‘we praten hier morgen over’-moment?"},
  {type:"Majority", text:"Wie is het meest waarschijnlijk om precies de verkeerde persoon te vertrouwen met navigatie?"},
  {type:"Majority", text:"Wie gaat als eerste iets kwijt zijn en heel overtuigend zeggen dat iemand anders het had?"},
  {type:"Majority", text:"Wie heeft de grootste kans om een groepsfoto te verpesten en daarna te zeggen dat hij/zij hem juist redde?"},
  {type:"Majority", text:"Wie wordt waarschijnlijk de commentator van de avond?"},
  {type:"Majority", text:"Wie heeft de meeste kans om een dramatische monoloog te houden over vriendschap?"},
  {type:"Majority", text:"Wie gaat op zondag het meeste doen alsof hij/zij nergens last van heeft?"},
  {type:"Majority", text:"Wie gaat het vaakst ‘ik zweer het’ zeggen in een verhaal dat steeds minder geloofwaardig wordt?"},
  {type:"Majority", text:"Wie is het meest waarschijnlijk om een bar binnen te lopen en meteen te zeggen: ‘dit is de vibe’?"},
  {type:"Majority", text:"Wie heeft het grootste talent voor chaos creëren zonder ooit verantwoordelijkheid te nemen?"},
  {type:"Majority", text:"Wie zou in een noodsituatie eerst een grap maken en daarna pas helpen?"},
  {type:"Majority", text:"Wie heeft de meeste kans om bij thuiskomst te zeggen: ‘we moeten dit vaker doen’ en dan 3 dagen stil te zijn?"},
  {type:"Majority", text:"Wie gaat tijdens de rit al praten alsof we op aftermovie-materiaal zitten?"},
  {type:"Majority", text:"Wie wordt de persoon die elke keuze ‘strategisch’ noemt, ook als het gewoon dom is?"}
];
